server:
  port: 8080

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: client-service
          uri: lb://client-service
          predicates:
            - Path=/api/v1/clients/**
        - id: discount-service
          uri: lb://discount-service
          predicates:
            - Path=/api/v1/discounts/**
        - id: rate-service
          uri: lb://rate-service
          predicates:
            - Path=/api/v1/rates/**   
        - id: kart-service
          uri: lb://kart-service
          predicates:
            - Path=/api/v1/karts/**     
        - id: reservation-service
          uri: lb://reservation-service
          predicates:
            - Path=/api/v1/reservations/**