apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-microservice
  labels:
    app: frontend-microservice
spec:
  selector:
    matchLabels:
      app: frontend-microservice
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-microservice
    spec:
      containers:
        - name: gokart-microservice-frontend
          image: docriser97/gokart-microservice-frontend
          ports:
          - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: gokart-microservice-frontend
  labels:
    app: gokart-microservice-frontend
spec:
  type: NodePort
  selector:
    app: frontend-microservice
  ports:
    - protocol: TCP
      port: 80        
      targetPort: 80   
      nodePort: 30080   
