apiVersion: apps/v1
kind: Deployment
metadata:
  name: kart-microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kart-microservice
  template:
    metadata:
      labels:
        app: kart-microservice
    spec:
      containers:
      - name: kart-microservice
        image: docriser97/kart-service-backend:latest
        ports:
        - containerPort: 8080
        env:
        - name: POSTGRES_DB_KART
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_KART
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"

---
apiVersion: v1
kind: Service
metadata:
  name: kart-service
spec:
  type: ClusterIP
  selector:
    app: kart-microservice
  ports:
  - port: 80
    targetPort: 8080
