apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB_CLIENT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_CLIENT
        - name: POSTGRES_DB_KART
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_KART
        - name: POSTGRES_DB_RATE
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_RATE
        - name: POSTGRES_DB_DISCOUNT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_DISCOUNT
        - name: POSTGRES_DB_DISCOUNT_DAY
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_DISCOUNT_DAY
        - name: POSTGRES_DB_DISCOUNT_VISIT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_DISCOUNT_VISIT
        - name: POSTGRES_DB_RESERVATION
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_RESERVATION
        - name: POSTGRES_DB_PAYMENT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_PAYMENT
        - name: POSTGRES_DB_REPORT
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_REPORT
        - name: POSTGRES_DB_WEEKLYRACK
          valueFrom:
            configMapKeyRef:
              name: postgres-config
              key: POSTGRES_DB_WEEKLYRACK
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: postgres-storage
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres